name: Windows 2025 (Pinggy SSL Tunnel)

on: workflow_dispatch

jobs:
  build:
    runs-on: windows-2025
    timeout-minutes: 9999

    steps:
    - name: Enable RDP Access and Create User
      run: |
        # 1. تفعيل خدمة الـ RDP وتخطي جدار الحماية للويندوز
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name "fDenyTSConnections" -Value 0
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -Name "UserAuthentication" -Value 1
        
        # 2. إنشاء مستخدم جديد بصلاحيات الـ Administrator للاتصال
        net user administrator JohnTech1234 /add
        net localgroup administrators administrator /add

    - name: Start Pinggy TCP Tunnel (RDP 3389)
      run: |
        # 3. تشغيل النفق عبر بورت 443 المحمي لتفادي الـ Block وحظر الـ SSH
        ssh -o StrictHostKeyChecking=no -p 443 -R 0:localhost:3389 rdp@a.pinggy.io
